# Generated by Django 4.2.7 on 2023-12-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                ("vendor_code", models.CharField(max_length=50, unique=True)),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
            ],
            options={
                "db_table": "Vendor",
                "indexes": [
                    models.Index(fields=["name"], name="Vendor_name_be7c46_idx"),
                    models.Index(
                        fields=["vendor_code"], name="Vendor_vendor__b0a190_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField()),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quality_rating", models.FloatField(blank=True, null=True)),
                ("issue_date", models.DateTimeField()),
                ("acknowledgment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
            ],
            options={
                "db_table": "PurchaseOrder",
                "indexes": [
                    models.Index(
                        fields=["po_number"], name="PurchaseOrd_po_numb_30a067_idx"
                    ),
                    models.Index(
                        fields=["order_date"], name="PurchaseOrd_order_d_f19b6b_idx"
                    ),
                    models.Index(
                        fields=["delivery_date"], name="PurchaseOrd_deliver_529afc_idx"
                    ),
                    models.Index(
                        fields=["status"], name="PurchaseOrd_status_16d03d_idx"
                    ),
                    models.Index(
                        fields=["issue_date"], name="PurchaseOrd_issue_d_37274d_idx"
                    ),
                    models.Index(
                        fields=["acknowledgment_date"],
                        name="PurchaseOrd_acknowl_4f80aa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vendor"
                    ),
                ),
            ],
            options={
                "db_table": "HistoricalPerformance",
                "indexes": [
                    models.Index(fields=["date"], name="HistoricalP_date_2651c7_idx")
                ],
            },
        ),
    ]
