# Generated by Django 4.2.7 on 2023-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_historicalperformance_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                db_column="status",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["expected_delivery_date"], name="PurchaseOrd_expecte_a93a4e_idx"
            ),
        ),
    ]
