# Generated by Django 4.2.7 on 2023-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_purchaseorder_expected_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
